### ISSUE TITLE
Reporting Live Validation For an API version of a Specific RP

### ISSUE THREAD

**Issue by salameer** [Azure/oav-express#15]
The ask here is to enable on demand Report generation of the Live Validation for a version of a swagger for a specific RP.

For the Example, a report would be like this:

RP: Microsoft Network

Swagger RP Version: 2017-09-01

For each of the operations across all swaggers in there:

|Operation Name | Found instance online? (Y/N) | Valid Reuqest Found? (Y/N) | Valid Response Found? (Y/Y)

**Comment by salameer** [comment]
Hey valid,

Please work with @veronicagg once you have a plan in mind, she can definitely help support you in this space. and of-course the infamous @johanste

**Comment by vladbarosan** [comment]
This is done for the new dynamic validation models here https://github.com/vladbarosan/openapi-platform
